export enum FlatFormControlType {
  INPUT_TEXT = 'INPUT_TEXT',
  INPUT_NUMBER = 'INPUT_NUMBER',
  INPUT_PASSWORD = 'INPUT_PASSWORD',
  INPUT_EMAIL = 'INPUT_EMAIL',
  INPUT_DATE = 'INPUT_DATE',
  TEXTAREA = 'TEXTAREA',
  SELECT = 'SELECT',
}
